/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class Delete_AudioVisual extends javax.swing.JFrame {

    /**
     * Creates new form Delete_AudioVisual
     */
    public Delete_AudioVisual() {
        initComponents();
         this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Delete AudioVisual");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_DeleteAudioVisual = new javax.swing.JLabel();
        lb_SeekDeleteAudioVisual = new javax.swing.JLabel();
        tf_SeekDeleteAudioVisual = new javax.swing.JTextField();
        btn_SeekDeleteAudioVisual = new javax.swing.JButton();
        lb_NameDeleteAudioVisual = new javax.swing.JLabel();
        lb_CodeDeleteAudioVisual = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_BrandDeleteAudioVisual = new javax.swing.JLabel();
        lb_FuntionDeleteAudioVisual = new javax.swing.JLabel();
        tf_NameDeleteAudioVisual = new javax.swing.JTextField();
        tf_CodeDeleteAudioVisual = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        tf_BrandDeleteAudioVisual = new javax.swing.JTextField();
        tf_FuntionDeleteAudioVisual = new javax.swing.JTextField();
        btn_DeleteAudioVisual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_DeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_DeleteAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_DeleteAudioVisual.setText("Delete AudioVisual");

        lb_SeekDeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_SeekDeleteAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_SeekDeleteAudioVisual.setText("Enter the code of the AudioVisual to delete");

        btn_SeekDeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_SeekDeleteAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        btn_SeekDeleteAudioVisual.setText("Seek");
        btn_SeekDeleteAudioVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeekDeleteAudioVisualActionPerformed(evt);
            }
        });

        lb_NameDeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_NameDeleteAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_NameDeleteAudioVisual.setText("Name");

        lb_CodeDeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CodeDeleteAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_CodeDeleteAudioVisual.setText("Code");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("jLabel5");

        lb_BrandDeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_BrandDeleteAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_BrandDeleteAudioVisual.setText("Brand");

        lb_FuntionDeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_FuntionDeleteAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_FuntionDeleteAudioVisual.setText("Funtion");

        btn_DeleteAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_DeleteAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        btn_DeleteAudioVisual.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_SeekDeleteAudioVisual)
                    .addComponent(lb_FuntionDeleteAudioVisual)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lb_DeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_NameDeleteAudioVisual)
                                .addComponent(lb_CodeDeleteAudioVisual)
                                .addComponent(jLabel5)
                                .addComponent(lb_BrandDeleteAudioVisual))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_FuntionDeleteAudioVisual, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(tf_NameDeleteAudioVisual)
                                .addComponent(tf_CodeDeleteAudioVisual)
                                .addComponent(jTextField4)
                                .addComponent(tf_BrandDeleteAudioVisual))
                            .addGap(44, 44, 44)
                            .addComponent(btn_DeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)))
                    .addComponent(tf_SeekDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btn_SeekDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_DeleteAudioVisual)
                .addGap(35, 35, 35)
                .addComponent(lb_SeekDeleteAudioVisual)
                .addGap(18, 18, 18)
                .addComponent(tf_SeekDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_SeekDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NameDeleteAudioVisual)
                    .addComponent(tf_NameDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CodeDeleteAudioVisual)
                    .addComponent(tf_CodeDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_BrandDeleteAudioVisual)
                    .addComponent(tf_BrandDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_FuntionDeleteAudioVisual)
                    .addComponent(tf_FuntionDeleteAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SeekDeleteAudioVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeekDeleteAudioVisualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SeekDeleteAudioVisualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_AudioVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeleteAudioVisual;
    private javax.swing.JButton btn_SeekDeleteAudioVisual;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lb_BrandDeleteAudioVisual;
    private javax.swing.JLabel lb_CodeDeleteAudioVisual;
    private javax.swing.JLabel lb_DeleteAudioVisual;
    private javax.swing.JLabel lb_FuntionDeleteAudioVisual;
    private javax.swing.JLabel lb_NameDeleteAudioVisual;
    private javax.swing.JLabel lb_SeekDeleteAudioVisual;
    private javax.swing.JTextField tf_BrandDeleteAudioVisual;
    private javax.swing.JTextField tf_CodeDeleteAudioVisual;
    private javax.swing.JTextField tf_FuntionDeleteAudioVisual;
    private javax.swing.JTextField tf_NameDeleteAudioVisual;
    private javax.swing.JTextField tf_SeekDeleteAudioVisual;
    // End of variables declaration//GEN-END:variables
}
