/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class Delete_Student extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Student
     */
    public Delete_Student() {
        initComponents();
         this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Delete a Student");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_DeleteStudent = new javax.swing.JLabel();
        lb_SeekDeleteStudent = new javax.swing.JLabel();
        tf_SeekDeleteStudent = new javax.swing.JTextField();
        btn_SeekDeleteStudent = new javax.swing.JButton();
        lb_NameDeleteStudent = new javax.swing.JLabel();
        lb_CodeDeleteStudent = new javax.swing.JLabel();
        lb_YearDeleteStudent = new javax.swing.JLabel();
        lb_CareerDeleteStudent = new javax.swing.JLabel();
        tf_NameDeleteStudent = new javax.swing.JTextField();
        tf_CodeDeleteStudent = new javax.swing.JTextField();
        tf_YearDeleteStudent = new javax.swing.JTextField();
        tf_CareerDeleteStudent = new javax.swing.JTextField();
        btn_DeleteStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_DeleteStudent.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_DeleteStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_DeleteStudent.setText("Delete a Student");

        lb_SeekDeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_SeekDeleteStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_SeekDeleteStudent.setText("Enter the code of the student to delete");

        btn_SeekDeleteStudent.setText("Seek");

        lb_NameDeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_NameDeleteStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_NameDeleteStudent.setText("Name");

        lb_CodeDeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CodeDeleteStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_CodeDeleteStudent.setText("Code");

        lb_YearDeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_YearDeleteStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_YearDeleteStudent.setText("year");

        lb_CareerDeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CareerDeleteStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_CareerDeleteStudent.setText("Careeer");

        btn_DeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_DeleteStudent.setForeground(new java.awt.Color(0, 0, 204));
        btn_DeleteStudent.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_SeekDeleteStudent)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_NameDeleteStudent)
                                    .addComponent(lb_CodeDeleteStudent)
                                    .addComponent(lb_YearDeleteStudent)
                                    .addComponent(lb_CareerDeleteStudent))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_NameDeleteStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tf_CodeDeleteStudent)
                                    .addComponent(tf_YearDeleteStudent)
                                    .addComponent(tf_CareerDeleteStudent)))
                            .addComponent(tf_SeekDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(lb_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btn_SeekDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lb_DeleteStudent)
                .addGap(33, 33, 33)
                .addComponent(lb_SeekDeleteStudent)
                .addGap(26, 26, 26)
                .addComponent(tf_SeekDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SeekDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NameDeleteStudent)
                    .addComponent(tf_NameDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CodeDeleteStudent)
                    .addComponent(tf_CodeDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_YearDeleteStudent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_YearDeleteStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CareerDeleteStudent)
                    .addComponent(tf_CareerDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeleteStudent;
    private javax.swing.JButton btn_SeekDeleteStudent;
    private javax.swing.JLabel lb_CareerDeleteStudent;
    private javax.swing.JLabel lb_CodeDeleteStudent;
    private javax.swing.JLabel lb_DeleteStudent;
    private javax.swing.JLabel lb_NameDeleteStudent;
    private javax.swing.JLabel lb_SeekDeleteStudent;
    private javax.swing.JLabel lb_YearDeleteStudent;
    private javax.swing.JTextField tf_CareerDeleteStudent;
    private javax.swing.JTextField tf_CodeDeleteStudent;
    private javax.swing.JTextField tf_NameDeleteStudent;
    private javax.swing.JTextField tf_SeekDeleteStudent;
    private javax.swing.JTextField tf_YearDeleteStudent;
    // End of variables declaration//GEN-END:variables
}
