/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class Insert_Student extends javax.swing.JFrame {

    /**
     * Creates new form Insert_Student
     */
    public Insert_Student() {
        initComponents();
         this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Add a new Student");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_NewStudent = new javax.swing.JLabel();
        lb_NameNewStudent = new javax.swing.JLabel();
        tf_NameNewStudent = new javax.swing.JTextField();
        lb_CodeNewStudent = new javax.swing.JLabel();
        tf_CodeNewStudent = new javax.swing.JTextField();
        lb_YearNewStudent = new javax.swing.JLabel();
        lb_CareerNewStudent = new javax.swing.JLabel();
        tf_YearNewStudent = new javax.swing.JTextField();
        bnt_NewStudent = new javax.swing.JButton();
        cb_CareerNewStudent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_NewStudent.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_NewStudent.setForeground(new java.awt.Color(51, 0, 255));
        lb_NewStudent.setText("Add a new Student");

        lb_NameNewStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_NameNewStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_NameNewStudent.setText("Name");

        lb_CodeNewStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_CodeNewStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_CodeNewStudent.setText("Code");

        lb_YearNewStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_YearNewStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_YearNewStudent.setText("Year");

        lb_CareerNewStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_CareerNewStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_CareerNewStudent.setText("Career");

        bnt_NewStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bnt_NewStudent.setForeground(new java.awt.Color(51, 0, 204));
        bnt_NewStudent.setText("Insert");

        cb_CareerNewStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Career", "Agronomy", "Computing", "Education" }));
        cb_CareerNewStudent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_CareerNewStudentItemStateChanged(evt);
            }
        });
        cb_CareerNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CareerNewStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lb_NewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lb_NameNewStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_CareerNewStudent)
                            .addComponent(tf_NameNewStudent)
                            .addComponent(lb_CodeNewStudent)
                            .addComponent(tf_CodeNewStudent)
                            .addComponent(tf_YearNewStudent)
                            .addComponent(cb_CareerNewStudent, 0, 170, Short.MAX_VALUE))))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lb_YearNewStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnt_NewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lb_NewStudent)
                .addGap(41, 41, 41)
                .addComponent(lb_NameNewStudent)
                .addGap(18, 18, 18)
                .addComponent(tf_NameNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lb_CodeNewStudent)
                .addGap(37, 37, 37)
                .addComponent(tf_CodeNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lb_YearNewStudent))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(bnt_NewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(tf_YearNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(lb_CareerNewStudent)
                .addGap(30, 30, 30)
                .addComponent(cb_CareerNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_CareerNewStudentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_CareerNewStudentItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CareerNewStudentItemStateChanged

    private void cb_CareerNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CareerNewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CareerNewStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_NewStudent;
    private javax.swing.JComboBox<String> cb_CareerNewStudent;
    private javax.swing.JLabel lb_CareerNewStudent;
    private javax.swing.JLabel lb_CodeNewStudent;
    private javax.swing.JLabel lb_NameNewStudent;
    private javax.swing.JLabel lb_NewStudent;
    private javax.swing.JLabel lb_YearNewStudent;
    private javax.swing.JTextField tf_CodeNewStudent;
    private javax.swing.JTextField tf_NameNewStudent;
    private javax.swing.JTextField tf_YearNewStudent;
    // End of variables declaration//GEN-END:variables
}
