/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class Insert_AudioVisual extends javax.swing.JFrame {

    /**
     * Creates new form InsertAudioVisual
     */
    public Insert_AudioVisual() {
        initComponents();
         this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Add a new AudioVisual");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_InsertAudioVisual = new javax.swing.JLabel();
        lb_NameInsertAudioVisual = new javax.swing.JLabel();
        lb_CodeInsertAudioVisual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_BrandInsertAudioVisual = new javax.swing.JLabel();
        lb_FuntionInsertAudioVisual = new javax.swing.JLabel();
        tf_NameInsertAudioVisual = new javax.swing.JTextField();
        tf_CodeInsertAudioVisual = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        tf_InsertAudioVisual = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        btn_InsertAudioVisual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_InsertAudioVisual.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_InsertAudioVisual.setForeground(new java.awt.Color(51, 0, 255));
        lb_InsertAudioVisual.setText("Insert AudioVisual");

        lb_NameInsertAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_NameInsertAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        lb_NameInsertAudioVisual.setText("Name");

        lb_CodeInsertAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CodeInsertAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        lb_CodeInsertAudioVisual.setText("Code");

        jLabel4.setText("jLabel4");

        lb_BrandInsertAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_BrandInsertAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_BrandInsertAudioVisual.setText("Brand");

        lb_FuntionInsertAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_FuntionInsertAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_FuntionInsertAudioVisual.setText("Funtion");

        jTextField3.setText("jTextField3");

        btn_InsertAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_InsertAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        btn_InsertAudioVisual.setText("Insert");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lb_InsertAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_BrandInsertAudioVisual)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_NameInsertAudioVisual)
                                            .addComponent(lb_CodeInsertAudioVisual)
                                            .addComponent(jLabel4))
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_FuntionInsertAudioVisual)
                                        .addGap(8, 8, 8)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_NameInsertAudioVisual, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(tf_CodeInsertAudioVisual)
                                    .addComponent(tf_InsertAudioVisual)
                                    .addComponent(jTextField5)
                                    .addComponent(btn_InsertAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb_InsertAudioVisual)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NameInsertAudioVisual)
                    .addComponent(tf_NameInsertAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CodeInsertAudioVisual)
                    .addComponent(tf_CodeInsertAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_BrandInsertAudioVisual)
                    .addComponent(tf_InsertAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_FuntionInsertAudioVisual)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(btn_InsertAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_AudioVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_InsertAudioVisual;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lb_BrandInsertAudioVisual;
    private javax.swing.JLabel lb_CodeInsertAudioVisual;
    private javax.swing.JLabel lb_FuntionInsertAudioVisual;
    private javax.swing.JLabel lb_InsertAudioVisual;
    private javax.swing.JLabel lb_NameInsertAudioVisual;
    private javax.swing.JTextField tf_CodeInsertAudioVisual;
    private javax.swing.JTextField tf_InsertAudioVisual;
    private javax.swing.JTextField tf_NameInsertAudioVisual;
    // End of variables declaration//GEN-END:variables
}
