/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import javax.swing.JFrame;

/**
 *
 * @author Melvin
 */
public class Main_Interfeces extends javax.swing.JFrame {

    /**
     * Creates new form Book_Interfeces
     */
    public Main_Interfeces() {
        initComponents();
        this.setTitle("BiblioTech Melvin-Josue");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopMain = new javax.swing.JDesktopPane();
        MenuBarBiblioTech = new javax.swing.JMenuBar();
        menuBook = new javax.swing.JMenu();
        menuAddBook = new javax.swing.JMenuItem();
        menuModifyBook = new javax.swing.JMenuItem();
        menuDeleteBook = new javax.swing.JMenuItem();
        menuAudioVisual = new javax.swing.JMenu();
        menuAddAudioVisual = new javax.swing.JMenuItem();
        menuModifyAudioVisual = new javax.swing.JMenuItem();
        menuDeleteAudioVisual = new javax.swing.JMenuItem();
        menuStudent = new javax.swing.JMenu();
        menuAddStudent = new javax.swing.JMenuItem();
        menuModifyStudent = new javax.swing.JMenuItem();
        menuDeleteStudent = new javax.swing.JMenuItem();
        menuLoan = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopMainLayout = new javax.swing.GroupLayout(DesktopMain);
        DesktopMain.setLayout(DesktopMainLayout);
        DesktopMainLayout.setHorizontalGroup(
            DesktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        DesktopMainLayout.setVerticalGroup(
            DesktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        MenuBarBiblioTech.setBackground(new java.awt.Color(0, 204, 51));
        MenuBarBiblioTech.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuBook.setForeground(new java.awt.Color(51, 0, 204));
        menuBook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melvin\\Desktop\\biblioteca-1.png")); // NOI18N
        menuBook.setText("Book");
        menuBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuAddBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuAddBook.setForeground(new java.awt.Color(0, 0, 204));
        menuAddBook.setText("Add");
        menuAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddBookActionPerformed(evt);
            }
        });
        menuBook.add(menuAddBook);

        menuModifyBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuModifyBook.setForeground(new java.awt.Color(51, 0, 204));
        menuModifyBook.setText("Modify");
        menuModifyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModifyBookActionPerformed(evt);
            }
        });
        menuBook.add(menuModifyBook);

        menuDeleteBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuDeleteBook.setForeground(new java.awt.Color(51, 0, 204));
        menuDeleteBook.setText("Delete");
        menuDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteBookActionPerformed(evt);
            }
        });
        menuBook.add(menuDeleteBook);

        MenuBarBiblioTech.add(menuBook);

        menuAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        menuAudioVisual.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melvin\\Desktop\\contrasena.png")); // NOI18N
        menuAudioVisual.setText("  AudioVisual");
        menuAudioVisual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuAddAudioVisual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuAddAudioVisual.setForeground(new java.awt.Color(51, 0, 255));
        menuAddAudioVisual.setText("Add");
        menuAddAudioVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddAudioVisualActionPerformed(evt);
            }
        });
        menuAudioVisual.add(menuAddAudioVisual);

        menuModifyAudioVisual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuModifyAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        menuModifyAudioVisual.setText("Modify");
        menuModifyAudioVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModifyAudioVisualActionPerformed(evt);
            }
        });
        menuAudioVisual.add(menuModifyAudioVisual);

        menuDeleteAudioVisual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuDeleteAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        menuDeleteAudioVisual.setText("Delete");
        menuDeleteAudioVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteAudioVisualActionPerformed(evt);
            }
        });
        menuAudioVisual.add(menuDeleteAudioVisual);

        MenuBarBiblioTech.add(menuAudioVisual);

        menuStudent.setForeground(new java.awt.Color(0, 0, 255));
        menuStudent.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melvin\\Desktop\\pensamiento.png")); // NOI18N
        menuStudent.setText("  Student");
        menuStudent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuAddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuAddStudent.setForeground(new java.awt.Color(0, 0, 204));
        menuAddStudent.setText("Add");
        menuAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddStudentActionPerformed(evt);
            }
        });
        menuStudent.add(menuAddStudent);

        menuModifyStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuModifyStudent.setForeground(new java.awt.Color(51, 0, 255));
        menuModifyStudent.setText("Modify");
        menuModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModifyStudentActionPerformed(evt);
            }
        });
        menuStudent.add(menuModifyStudent);

        menuDeleteStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuDeleteStudent.setForeground(new java.awt.Color(51, 0, 255));
        menuDeleteStudent.setText("Delete");
        menuDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteStudentActionPerformed(evt);
            }
        });
        menuStudent.add(menuDeleteStudent);

        MenuBarBiblioTech.add(menuStudent);

        menuLoan.setBackground(new java.awt.Color(0, 204, 51));
        menuLoan.setForeground(new java.awt.Color(51, 0, 204));
        menuLoan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melvin\\Desktop\\empleado.png")); // NOI18N
        menuLoan.setText("  Loan");
        menuLoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(51, 0, 204));
        jMenuItem1.setText("New Loan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuLoan.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(51, 0, 204));
        jMenuItem4.setText("Modify Loan");
        menuLoan.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(51, 0, 204));
        jMenuItem5.setText("Cancel Loan");
        menuLoan.add(jMenuItem5);

        MenuBarBiblioTech.add(menuLoan);

        setJMenuBar(MenuBarBiblioTech);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesktopMain))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesktopMain))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModifyStudentActionPerformed
        Modify_Student modifystudent = new Modify_Student();
        modifystudent.show();
        modifystudent.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuModifyStudentActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddBookActionPerformed
       
        Insert_Book insertbook = new Insert_Book();
        insertbook.show();
        insertbook.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuAddBookActionPerformed

    private void menuDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteBookActionPerformed
       
        Delete_Book deletebook = new Delete_Book();
        deletebook.show();
        deletebook.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuDeleteBookActionPerformed

    private void menuModifyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModifyBookActionPerformed
        
        Modify_Book modifybook = new Modify_Book();
        modifybook.show();
        modifybook.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuModifyBookActionPerformed

    private void menuAddAudioVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddAudioVisualActionPerformed
        
        Insert_AudioVisual insertaudiovisual = new Insert_AudioVisual();
        insertaudiovisual.show();
        insertaudiovisual.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuAddAudioVisualActionPerformed

    private void menuModifyAudioVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModifyAudioVisualActionPerformed
       
        Modify_AudioVisual modifyaudiovisual = new Modify_AudioVisual();
        modifyaudiovisual.show();
        modifyaudiovisual.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuModifyAudioVisualActionPerformed

    private void menuDeleteAudioVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteAudioVisualActionPerformed
        
        Delete_AudioVisual deleaudiovisual = new Delete_AudioVisual();
        deleaudiovisual.show();
        deleaudiovisual.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuDeleteAudioVisualActionPerformed

    private void menuAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddStudentActionPerformed
       Insert_Student inserestudent = new Insert_Student();
       inserestudent.show();
       inserestudent.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuAddStudentActionPerformed

    private void menuDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteStudentActionPerformed
      Delete_Student deletestudent = new Delete_Student();
      deletestudent.show();
      deletestudent.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuDeleteStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Interfeces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Interfeces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Interfeces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Interfeces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Interfeces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopMain;
    private javax.swing.JMenuBar MenuBarBiblioTech;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem menuAddAudioVisual;
    private javax.swing.JMenuItem menuAddBook;
    private javax.swing.JMenuItem menuAddStudent;
    private javax.swing.JMenu menuAudioVisual;
    private javax.swing.JMenu menuBook;
    private javax.swing.JMenuItem menuDeleteAudioVisual;
    private javax.swing.JMenuItem menuDeleteBook;
    private javax.swing.JMenuItem menuDeleteStudent;
    private javax.swing.JMenu menuLoan;
    private javax.swing.JMenuItem menuModifyAudioVisual;
    private javax.swing.JMenuItem menuModifyBook;
    private javax.swing.JMenuItem menuModifyStudent;
    private javax.swing.JMenu menuStudent;
    // End of variables declaration//GEN-END:variables
}
