/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class Modify_AudioVisual extends javax.swing.JFrame {

    /**
     * Creates new form Modify_AudioVisual
     */
    public Modify_AudioVisual() {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Modify AudioVisual");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_ModifyAudioVisual = new javax.swing.JLabel();
        lb_SeekModifyAudioVisual = new javax.swing.JLabel();
        tf_SeekModifyAudioVisual = new javax.swing.JTextField();
        btn_seekModifyAudioVisual = new javax.swing.JButton();
        lb_NameModifyAudioVisual = new javax.swing.JLabel();
        lb_CodeModifyAudioVisual = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_BrandModifyAudioVisual = new javax.swing.JLabel();
        lb_FuntionModifyAudioVisual = new javax.swing.JLabel();
        tf_NameModifyAudioVisual = new javax.swing.JTextField();
        tf_CodeModifyAudioVisual = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        tf_BrandModifyAudioVisual = new javax.swing.JTextField();
        tf_FuntionModifyAudioVisual = new javax.swing.JTextField();
        btn_ModifyAudioVisual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_ModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_ModifyAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_ModifyAudioVisual.setText("Modify AudioVisual");

        lb_SeekModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_SeekModifyAudioVisual.setForeground(new java.awt.Color(0, 0, 153));
        lb_SeekModifyAudioVisual.setText("Enter the code of the AudioVisual to modify");

        btn_seekModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_seekModifyAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        btn_seekModifyAudioVisual.setText("Seek");

        lb_NameModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_NameModifyAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        lb_NameModifyAudioVisual.setText("Name");

        lb_CodeModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CodeModifyAudioVisual.setForeground(new java.awt.Color(0, 0, 204));
        lb_CodeModifyAudioVisual.setText("Code");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("jLabel5");

        lb_BrandModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_BrandModifyAudioVisual.setForeground(new java.awt.Color(0, 0, 153));
        lb_BrandModifyAudioVisual.setText("Brand");

        lb_FuntionModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_FuntionModifyAudioVisual.setForeground(new java.awt.Color(51, 0, 204));
        lb_FuntionModifyAudioVisual.setText("Funtion");

        btn_ModifyAudioVisual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ModifyAudioVisual.setForeground(new java.awt.Color(0, 0, 153));
        btn_ModifyAudioVisual.setText("Modify");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_SeekModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_SeekModifyAudioVisual)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_NameModifyAudioVisual)
                            .addComponent(lb_CodeModifyAudioVisual)
                            .addComponent(jLabel5)
                            .addComponent(lb_BrandModifyAudioVisual)
                            .addComponent(lb_FuntionModifyAudioVisual))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_NameModifyAudioVisual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tf_CodeModifyAudioVisual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_BrandModifyAudioVisual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_FuntionModifyAudioVisual, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(110, 110, 110)
                        .addComponent(btn_ModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lb_ModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btn_seekModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_ModifyAudioVisual)
                .addGap(36, 36, 36)
                .addComponent(lb_SeekModifyAudioVisual)
                .addGap(18, 18, 18)
                .addComponent(tf_SeekModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_seekModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NameModifyAudioVisual)
                    .addComponent(tf_NameModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CodeModifyAudioVisual)
                    .addComponent(tf_CodeModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_BrandModifyAudioVisual)
                    .addComponent(tf_BrandModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_FuntionModifyAudioVisual)
                    .addComponent(tf_FuntionModifyAudioVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify_AudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify_AudioVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ModifyAudioVisual;
    private javax.swing.JButton btn_seekModifyAudioVisual;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lb_BrandModifyAudioVisual;
    private javax.swing.JLabel lb_CodeModifyAudioVisual;
    private javax.swing.JLabel lb_FuntionModifyAudioVisual;
    private javax.swing.JLabel lb_ModifyAudioVisual;
    private javax.swing.JLabel lb_NameModifyAudioVisual;
    private javax.swing.JLabel lb_SeekModifyAudioVisual;
    private javax.swing.JTextField tf_BrandModifyAudioVisual;
    private javax.swing.JTextField tf_CodeModifyAudioVisual;
    private javax.swing.JTextField tf_FuntionModifyAudioVisual;
    private javax.swing.JTextField tf_NameModifyAudioVisual;
    private javax.swing.JTextField tf_SeekModifyAudioVisual;
    // End of variables declaration//GEN-END:variables
}
