/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class Modify_Book extends javax.swing.JFrame {

    /**
     * Creates new form ModifyBook
     */
    public Modify_Book() {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Modify a Book");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_ModifyBook = new javax.swing.JLabel();
        lb_SeekModifyBook = new javax.swing.JLabel();
        tf_SeekModifyBook = new javax.swing.JTextField();
        btn_seekModifyBook = new javax.swing.JButton();
        lb_NameModifyBook = new javax.swing.JLabel();
        lb_CodeModifyBook = new javax.swing.JLabel();
        lb_AuthorModifyBook = new javax.swing.JLabel();
        lb_EditorialModifyBook = new javax.swing.JLabel();
        lb_ShapeModifyBook = new javax.swing.JLabel();
        tf_NameModifyBook = new javax.swing.JTextField();
        tf_CodeModifyBook = new javax.swing.JTextField();
        tf_AuthorModifyBook = new javax.swing.JTextField();
        tf_EditorialModifyBook = new javax.swing.JTextField();
        tf_ShapeModifyBook = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_ModifyBook.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_ModifyBook.setForeground(new java.awt.Color(51, 0, 204));
        lb_ModifyBook.setText("Modify Book");

        lb_SeekModifyBook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_SeekModifyBook.setForeground(new java.awt.Color(51, 0, 255));
        lb_SeekModifyBook.setText("Enter the code of the book to modify");

        btn_seekModifyBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_seekModifyBook.setForeground(new java.awt.Color(51, 0, 255));
        btn_seekModifyBook.setText("Seek");

        lb_NameModifyBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_NameModifyBook.setForeground(new java.awt.Color(0, 0, 204));
        lb_NameModifyBook.setText("Name");

        lb_CodeModifyBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_CodeModifyBook.setForeground(new java.awt.Color(0, 0, 204));
        lb_CodeModifyBook.setText("Code");

        lb_AuthorModifyBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_AuthorModifyBook.setForeground(new java.awt.Color(51, 0, 204));
        lb_AuthorModifyBook.setText("Author");

        lb_EditorialModifyBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_EditorialModifyBook.setForeground(new java.awt.Color(51, 0, 204));
        lb_EditorialModifyBook.setText("Editorial");

        lb_ShapeModifyBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_ShapeModifyBook.setForeground(new java.awt.Color(51, 0, 204));
        lb_ShapeModifyBook.setText("Shape");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 204));
        jButton1.setText("Modify");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_SeekModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_seekModifyBook, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 12, Short.MAX_VALUE)
                                            .addComponent(lb_SeekModifyBook))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lb_CodeModifyBook)
                                                .addComponent(lb_AuthorModifyBook)
                                                .addComponent(lb_EditorialModifyBook)
                                                .addComponent(lb_NameModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lb_ShapeModifyBook))
                                            .addGap(59, 59, 59)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_NameModifyBook, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                                .addComponent(tf_CodeModifyBook)
                                                .addComponent(tf_AuthorModifyBook)
                                                .addComponent(tf_EditorialModifyBook)
                                                .addComponent(tf_ShapeModifyBook))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGap(60, 60, 60)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(lb_ModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_ModifyBook)
                .addGap(29, 29, 29)
                .addComponent(lb_SeekModifyBook)
                .addGap(18, 18, 18)
                .addComponent(tf_SeekModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_seekModifyBook)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NameModifyBook)
                    .addComponent(tf_NameModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CodeModifyBook)
                    .addComponent(tf_CodeModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_AuthorModifyBook)
                    .addComponent(tf_AuthorModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_EditorialModifyBook)
                    .addComponent(tf_EditorialModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ShapeModifyBook)
                    .addComponent(tf_ShapeModifyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_seekModifyBook;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_AuthorModifyBook;
    private javax.swing.JLabel lb_CodeModifyBook;
    private javax.swing.JLabel lb_EditorialModifyBook;
    private javax.swing.JLabel lb_ModifyBook;
    private javax.swing.JLabel lb_NameModifyBook;
    private javax.swing.JLabel lb_SeekModifyBook;
    private javax.swing.JLabel lb_ShapeModifyBook;
    private javax.swing.JTextField tf_AuthorModifyBook;
    private javax.swing.JTextField tf_CodeModifyBook;
    private javax.swing.JTextField tf_EditorialModifyBook;
    private javax.swing.JTextField tf_NameModifyBook;
    private javax.swing.JTextField tf_SeekModifyBook;
    private javax.swing.JTextField tf_ShapeModifyBook;
    // End of variables declaration//GEN-END:variables
}
