/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import java.awt.Color;

/**
 *
 * @author Melvin
 */
public class Modify_Student extends javax.swing.JFrame {

    /**
     * Creates new form Modify_Student
     */
    public Modify_Student() {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Modify a Student");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_ModifyStudent = new javax.swing.JLabel();
        lb_SeekModifyStudent = new javax.swing.JLabel();
        tf_SeekModifyStudent = new javax.swing.JTextField();
        btn_SeekModifyStudent = new javax.swing.JButton();
        lb_NameModifyStudent = new javax.swing.JLabel();
        lb_CodeModifyStudent = new javax.swing.JLabel();
        lb_YearModifyStudent = new javax.swing.JLabel();
        lb_CareerModifyStudent = new javax.swing.JLabel();
        tf_NameModifyStudent = new javax.swing.JTextField();
        tf_CodeModifyStudent = new javax.swing.JTextField();
        tf_YearModifyStudent = new javax.swing.JTextField();
        cb_CarrerModifyStudent = new javax.swing.JComboBox<>();
        btn_ModifyStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_ModifyStudent.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_ModifyStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_ModifyStudent.setText("Modify a Student");

        lb_SeekModifyStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_SeekModifyStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_SeekModifyStudent.setText("Enter the code of the student to modify");

        btn_SeekModifyStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_SeekModifyStudent.setForeground(new java.awt.Color(0, 0, 153));
        btn_SeekModifyStudent.setText("Seek");

        lb_NameModifyStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_NameModifyStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_NameModifyStudent.setText("Name");

        lb_CodeModifyStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CodeModifyStudent.setForeground(new java.awt.Color(0, 0, 255));
        lb_CodeModifyStudent.setText("Code");

        lb_YearModifyStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_YearModifyStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_YearModifyStudent.setText("Year");

        lb_CareerModifyStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CareerModifyStudent.setForeground(new java.awt.Color(0, 0, 204));
        lb_CareerModifyStudent.setText("Career");

        cb_CarrerModifyStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a item", "Agronomy", "Computing", "Education" }));

        btn_ModifyStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ModifyStudent.setForeground(new java.awt.Color(0, 0, 204));
        btn_ModifyStudent.setText("Modify");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lb_ModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_SeekModifyStudent, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lb_CodeModifyStudent)
                                                    .addComponent(lb_YearModifyStudent)
                                                    .addComponent(lb_CareerModifyStudent))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tf_CodeModifyStudent, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_YearModifyStudent, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cb_CarrerModifyStudent, javax.swing.GroupLayout.Alignment.LEADING, 0, 121, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lb_NameModifyStudent)
                                                .addGap(41, 41, 41)
                                                .addComponent(tf_NameModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(145, 145, 145)
                                .addComponent(btn_ModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_SeekModifyStudent)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btn_SeekModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_ModifyStudent)
                .addGap(37, 37, 37)
                .addComponent(lb_SeekModifyStudent)
                .addGap(34, 34, 34)
                .addComponent(tf_SeekModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_SeekModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NameModifyStudent)
                    .addComponent(tf_NameModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_CodeModifyStudent)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_CodeModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_YearModifyStudent)
                    .addComponent(tf_YearModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_CareerModifyStudent)
                    .addComponent(cb_CarrerModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ModifyStudent;
    private javax.swing.JButton btn_SeekModifyStudent;
    private javax.swing.JComboBox<String> cb_CarrerModifyStudent;
    private javax.swing.JLabel lb_CareerModifyStudent;
    private javax.swing.JLabel lb_CodeModifyStudent;
    private javax.swing.JLabel lb_ModifyStudent;
    private javax.swing.JLabel lb_NameModifyStudent;
    private javax.swing.JLabel lb_SeekModifyStudent;
    private javax.swing.JLabel lb_YearModifyStudent;
    private javax.swing.JTextField tf_CodeModifyStudent;
    private javax.swing.JTextField tf_NameModifyStudent;
    private javax.swing.JTextField tf_SeekModifyStudent;
    private javax.swing.JTextField tf_YearModifyStudent;
    // End of variables declaration//GEN-END:variables
}
